# About
authors: Shahar and Shlomi

[Github](https://github.com/shachar700/DataAnalysis_ElectricVehicles)

Column Name -	Description

VIN (1-10) - First 10 characters of the Vehicle Identification Number.

County - The county where the vehicle is registered or located.

City - The city where the vehicle is registered or located.

State - The U.S. state abbreviation (e.g., WA for Washington).

Postal Code - ZIP/postal code of the vehicle's location.

Model Year - The year the vehicle was manufactured.

Make - The manufacturer (e.g., Tesla, Nissan).

Model - The specific model of the car (e.g., Model 3, Leaf).

Electric Vehicle Type - Type of EV (Battery Electric Vehicle (BEV), Plug-in Hybrid Electric Vehicle (PHEV), etc.).

Clean Alternative Fuel Vehicle (CAFV) Eligibility - Indicates whether the vehicle qualifies under CAFV rules.

Electric Range - How many miles the vehicle can travel on electricity alone.

Base MSRP - Manufacturer's Suggested Retail Price at base level (starting price).

Legislative District - Legislative district associated with the vehicle's location.

DOL Vehicle ID - Department of Licensing Vehicle ID (state-assigned).

Vehicle Location - More detailed info about where the vehicle is located.

Electric Utility - The electric company servicing that area.

2020 Census Tract - Census tract identifier from the 2020 census (used for demographic/geographic analysis).

Questions:
- Vehicles per state
- Vehicles per county
- Vehicles per city
- Vehicles per legistrative district (handle na values)
- Vehicles per electric utility
- Top 7 companies with total amount of vehicles
- Top 7 models with total amount of vehicles
- Popular companies in each county
- Popular models in each county
- Electric Range per model (handle na values)

handle missing values: use Linear Regression/KNN to predict electric range,

split categories and turn them to binary values
dummies for Electric Utility and handle

# Installs

# Libraries

In [ ]:
import requests
import pandas as pd
import numpy as np

# Pre-process

In [ ]:
electric_vehicles_url = "https://raw.githubusercontent.com/shachar700/DataAnalysis_ElectricVehicles/refs/heads/main/data/Electric_Vehicle_Population_Data.csv"

def download_file(url, file_name):
  response = requests.get(url)
  if response.status_code == 200:
    with open(file_name, "wb") as file:
        file.write(response.content)
    print(f"Downloaded: {file_name}")

download_file(electric_vehicles_url, "electric_vehicles.csv")

Downloaded: electric_vehicles.csv

In [ ]:
df = pd.read_csv("/content/electric_vehicles.csv")
df.head(5)

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,5YJ3E1EBXK,King,Seattle,WA,98178.0,2019,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,220.0,0.0,37.0,477309682,POINT (-122.23825 47.49461),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
1,5YJYGDEE3L,Kitsap,Poulsbo,WA,98370.0,2020,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,291.0,0.0,23.0,109705683,POINT (-122.64681 47.73689),PUGET SOUND ENERGY INC,5.303509e+10
2,KM8KRDAF5P,Kitsap,Olalla,WA,98359.0,2023,HYUNDAI,IONIQ 5,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,0.0,26.0,230390492,POINT (-122.54729 47.42602),PUGET SOUND ENERGY INC,5.303509e+10
3,5UXTA6C0XM,Kitsap,Seabeck,WA,98380.0,2021,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,30.0,0.0,35.0,267929112,POINT (-122.81585 47.64509),PUGET SOUND ENERGY INC,5.303509e+10
4,JTMAB3FV7P,Thurston,Rainier,WA,98576.0,2023,TOYOTA,RAV4 PRIME,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,42.0,0.0,2.0,236505139,POINT (-122.68993 46.88897),PUGET SOUND ENERGY INC,5.306701e+10

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235692 entries, 0 to 235691
Data columns (total 17 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         235692 non-null  object
 1   County                                             235689 non-null  object
 2   City                                               235689 non-null  object
 3   State                                              235692 non-null  object
 4   Postal Code                                        235689 non-null  float64
 5   Model Year                                         235692 non-null  int64
 6   Make                                               235692 non-null  object
 7   Model                                              235692 non-null  object
 8   Electric Vehicle Type                              235692 non-null  object
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  235692 non-null  object
 10  Electric Range                                     235656 non-null  float64
 11  Base MSRP                                          235656 non-null  float64
 12  Legislative District                               235198 non-null  float64
 13  DOL Vehicle ID                                     235692 non-null  int64
 14  Vehicle Location                                   235682 non-null  object
 15  Electric Utility                                   235689 non-null  object
 16  2020 Census Tract                                  235689 non-null  float64
dtypes: float64(5), int64(2), object(10)
memory usage: 30.6+ MB

In [ ]:
df.describe()

         Postal Code     Model Year  Electric Range  Legislative District
count  235689.000000  235689.000000    95893.000000         235198.000000
mean    98177.656463    2021.406688      113.687506             28.879519
std      2524.218661       2.991909       98.454597             14.904644
min      1731.000000    2000.000000        6.000000              1.000000
25%     98052.000000    2020.000000       30.000000             17.000000
50%     98126.000000    2023.000000       72.000000             32.000000
75%     98374.000000    2024.000000      215.000000             42.000000
max     99577.000000    2025.000000      337.000000             49.000000

In [ ]:
df = df.drop(columns=["Base MSRP", "Vehicle Location", "DOL Vehicle ID", "2020 Census Tract"])

In [ ]:
#print(f"{df.isna().any(axis=1).sum()} rows")
display(df[df["County"].isna()])
df = df.dropna(subset=["County"])
df.loc[df["Electric Range"] == 0.0, "Electric Range"] = np.nan
display(df.isnull().sum())
df.head(3)

Empty DataFrame
Columns: [VIN (1-10), County, City, State, Postal Code, Model Year, Make, Model, Electric Vehicle Type, Clean Alternative Fuel Vehicle (CAFV) Eligibility, Electric Range, Legislative District, Vehicle Location, Electric Utility]
Index: []

VIN (1-10)                                                0
County                                                    0
City                                                      0
State                                                     0
Postal Code                                               0
Model Year                                                0
Make                                                      0
Model                                                     0
Electric Vehicle Type                                     0
Clean Alternative Fuel Vehicle (CAFV) Eligibility         0
Electric Range                                       139796
Legislative District                                    491
Vehicle Location                                          7
Electric Utility                                          0
dtype: int64

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,Vehicle Location,Electric Utility
0,5YJ3E1EBXK,King,Seattle,WA,98178.0,2019,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,220.0,37.0,POINT (-122.23825 47.49461),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)
1,5YJYGDEE3L,Kitsap,Poulsbo,WA,98370.0,2020,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,291.0,23.0,POINT (-122.64681 47.73689),PUGET SOUND ENERGY INC
2,KM8KRDAF5P,Kitsap,Olalla,WA,98359.0,2023,HYUNDAI,IONIQ 5,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,NaN,26.0,POINT (-122.54729 47.42602),PUGET SOUND ENERGY INC

In [ ]:
df['Make'].value_counts()

Make
TESLA                     101080
CHEVROLET                  17135
NISSAN                     15532
FORD                       12605
KIA                        11345
BMW                         9647
TOYOTA                      9478
HYUNDAI                     7406
RIVIAN                      6750
VOLKSWAGEN                  5976
JEEP                        5955
VOLVO                       5862
AUDI                        4360
CHRYSLER                    3786
MERCEDES-BENZ               2381
HONDA                       2134
SUBARU                      2012
PORSCHE                     1474
POLESTAR                    1260
CADILLAC                    1149
MINI                        1122
MITSUBISHI                  1114
MAZDA                       1020
LEXUS                        959
DODGE                        780
FIAT                         773
LUCID                        395
LINCOLN                      361
GMC                          360
GENESIS                      344
SMART                        242
JAGUAR                       241
ACURA                        203
FISKER                       183
LAND ROVER                   132
ALFA ROMEO                    97
BENTLEY                        6
BRIGHTDROP                     5
LAMBORGHINI                    5
TH!NK                          5
RAM                            4
AZURE DYNAMICS                 4
ROLLS-ROYCE                    4
VINFAST                        2
MULLEN AUTOMOTIVE INC.         2
WHEEGO ELECTRIC CARS           2
Name: count, dtype: int64

In [ ]:
df[['Make','Model']].value_counts()

Make                  Model
TESLA                 MODEL Y           49253
                      MODEL 3           36065
NISSAN                LEAF              13814
TESLA                 MODEL S            7885
CHEVROLET             BOLT EV            7278
                                        ...
TOYOTA                MIRAI                 2
WHEEGO ELECTRIC CARS  WHEEGO                2
CHEVROLET             BRIGHTDROP 400        1
PORSCHE               918                   1
MERCEDES-BENZ         SL-CLASS              1
Name: count, Length: 171, dtype: int64